-- Esquema de base de datos para Pau Pelus Beauty en Supabase
-- Pega todo este archivo en: Supabase → tu proyecto → SQL Editor → New query → Run

create extension if not exists pgcrypto;

create table productos (
  id uuid primary key default gen_random_uuid(),
  ref text unique not null,
  nombre text not null default '',
  color text default '',
  longitud text default '',
  tipo text default '',
  corte text default '',
  detalle text default '',
  precio numeric not null default 0,
  created_at timestamptz default now()
);

create table clientes (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  ciudad text default '',
  telefono text default '',
  notas text default '',
  created_at timestamptz default now()
);
create unique index clientes_nombre_norm_idx on clientes (lower(trim(nombre)));

create table compras (
  id uuid primary key default gen_random_uuid(),
  fecha date not null,
  proveedor text default '',
  ref text references productos(ref) on update cascade on delete set null,
  nombre text default '',
  cantidad integer not null check (cantidad > 0),
  costo_unitario numeric not null,
  costo_total numeric not null,
  created_at timestamptz default now()
);
create index idx_compras_ref_fecha on compras(ref, fecha);

create table ventas (
  id uuid primary key default gen_random_uuid(),
  numero integer generated by default as identity,
  fecha date not null,
  cliente_id uuid references clientes(id) on delete set null,
  cliente_nombre text not null default 'Cliente',
  ciudad text default 'Bogotá',
  total numeric not null default 0,
  costo_total numeric not null default 0,
  costo_envio numeric not null default 0,
  abono numeric not null default 0,
  saldo numeric not null default 0,
  utilidad numeric not null default 0,
  marcador text default null,
  liquidacion_id uuid, -- referencia a liquidaciones (FK creada abajo)
  created_at timestamptz default now()
);
create index idx_ventas_fecha on ventas(fecha);

create table liquidaciones (
  id uuid primary key default gen_random_uuid(),
  fecha_desde date not null,
  fecha_hasta date not null,
  total_ventas numeric not null default 0,
  total_costo numeric not null default 0,
  total_envios numeric not null default 0,
  utilidad numeric not null default 0,
  capital_paula numeric not null default 0,
  capital_diego numeric not null default 0,
  utilidad_paula numeric not null default 0,
  utilidad_diego numeric not null default 0,
  total_paula numeric not null default 0,
  total_diego numeric not null default 0,
  total_liquidado numeric not null default 0,
  notas text default '',
  created_at timestamptz default now()
);

alter table ventas add constraint fk_ventas_liquidacion foreign key (liquidacion_id) references liquidaciones(id) on delete set null;

create table venta_items (
  id uuid primary key default gen_random_uuid(),
  venta_id uuid references ventas(id) on delete cascade,
  ref text references productos(ref) on update cascade on delete set null,
  nombre text default '',
  cantidad integer not null check (cantidad > 0),
  precio numeric not null,
  subtotal numeric not null,
  costo_unitario numeric not null,
  costo_total numeric not null
);
create index idx_venta_items_ref on venta_items(ref);

create table entregas (
  id uuid primary key default gen_random_uuid(),
  venta_id uuid references ventas(id) on delete cascade unique not null,
  guia text default '',
  cliente_nombre text default 'Cliente',
  fecha date not null,
  monto numeric not null default 0,
  abono numeric not null default 0,
  saldo numeric not null default 0,
  empresa text default 'Por definir',
  created_at timestamptz default now()
);

create table pagos (
  id uuid primary key default gen_random_uuid(),
  entrega_id uuid references entregas(id) on delete cascade,
  fecha date not null,
  monto numeric not null,
  quien_paga text default 'Cliente',
  created_at timestamptz default now()
);

-- ================================================================
-- RLS: SOLO UNA PERSONA (LA DUEÑA) PUEDE LEER Y ESCRIBIR LOS DATOS.
-- La anon/publishable key que está en el navegador es pública por
-- diseño; la seguridad real la dan estas políticas. Antes cualquier
-- usuario autenticado tenía acceso total (using(true)); ahora solo
-- las que estén en la tabla app_users.
--
-- CONFIGURACIÓN ÚNICA (obligatoria antes de usar la app):
--   1. Supabase → SQL Editor → ejecuta:  select id, email from auth.users;
--   2. Copia el "id" de TU cuenta (la que usas para entrar a la app).
--   3. Reemplaza 'TU_ID_AQUI' en el INSERT de abajo y ejecútalo.
--   4. Desactiva los registros públicos: Authentication → Settings
--      → "Allow new users to sign up" = OFF.
-- ================================================================

create table if not exists public.app_users (
  id uuid primary key references auth.users(id) on delete cascade
);

-- 👇 PEGA AQUÍ TU UUID de auth.users:
insert into public.app_users (id) values ('TU_ID_AQUI')
on conflict (id) do nothing;

create or replace function public.usuario_autorizado()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.app_users a where a.id = auth.uid());
$$;

-- app_users solo se puede leer a si mismo (ni siquiera se ve la lista).
alter table public.app_users enable row level security;
create policy "ver_propio" on public.app_users
  for select using (auth.uid() = id);

alter table productos enable row level security;
alter table clientes enable row level security;
alter table compras enable row level security;
alter table ventas enable row level security;
alter table venta_items enable row level security;
alter table entregas enable row level security;
alter table pagos enable row level security;
alter table liquidaciones enable row level security;

-- Reemplazamos las políticas viejas por unas que solo permiten a la
-- dueña. El frontend usa siempre la anon key + login: si el usuario de
-- la sesión no está en app_users, no ve ni toca nada.
drop policy if exists "auth_full_access" on public.productos;
drop policy if exists "auth_full_access" on public.clientes;
drop policy if exists "auth_full_access" on public.compras;
drop policy if exists "auth_full_access" on public.ventas;
drop policy if exists "auth_full_access" on public.venta_items;
drop policy if exists "auth_full_access" on public.entregas;
drop policy if exists "auth_full_access" on public.pagos;

create policy "solo_duena" on public.productos   for all to authenticated using (public.usuario_autorizado()) with check (public.usuario_autorizado());
create policy "solo_duena" on public.clientes    for all to authenticated using (public.usuario_autorizado()) with check (public.usuario_autorizado());
create policy "solo_duena" on public.compras     for all to authenticated using (public.usuario_autorizado()) with check (public.usuario_autorizado());
create policy "solo_duena" on public.ventas      for all to authenticated using (public.usuario_autorizado()) with check (public.usuario_autorizado());
create policy "solo_duena" on public.venta_items for all to authenticated using (public.usuario_autorizado()) with check (public.usuario_autorizado());
create policy "solo_duena" on public.entregas    for all to authenticated using (public.usuario_autorizado()) with check (public.usuario_autorizado());
create policy "solo_duena" on public.pagos       for all to authenticated using (public.usuario_autorizado()) with check (public.usuario_autorizado());
create policy "solo_duena" on public.liquidaciones for all to authenticated using (public.usuario_autorizado()) with check (public.usuario_autorizado());
