-- Esquema de base de datos para Pau Pelus Beauty en Supabase
-- Pega todo este archivo en: Supabase → tu proyecto → SQL Editor → New query → Run

create extension if not exists pgcrypto;

create table productos (
  id uuid primary key default gen_random_uuid(),
  ref text unique not null,
  nombre text not null default '',
  color text default '',
  longitud text default '',
  tipo text default '',
  precio numeric not null default 0,
  created_at timestamptz default now()
);

create table clientes (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  ciudad text default '',
  telefono text default '',
  notas text default '',
  created_at timestamptz default now()
);
create unique index clientes_nombre_norm_idx on clientes (lower(trim(nombre)));

create table compras (
  id uuid primary key default gen_random_uuid(),
  fecha date not null,
  proveedor text default '',
  ref text references productos(ref) on update cascade on delete set null,
  nombre text default '',
  cantidad integer not null check (cantidad > 0),
  costo_unitario numeric not null,
  costo_total numeric not null,
  created_at timestamptz default now()
);
create index idx_compras_ref_fecha on compras(ref, fecha);

create table ventas (
  id uuid primary key default gen_random_uuid(),
  numero integer generated by default as identity,
  fecha date not null,
  cliente_id uuid references clientes(id) on delete set null,
  cliente_nombre text not null default 'Cliente',
  ciudad text default 'Bogotá',
  total numeric not null default 0,
  costo_total numeric not null default 0,
  costo_envio numeric not null default 0,
  abono numeric not null default 0,
  saldo numeric not null default 0,
  utilidad numeric not null default 0,
  created_at timestamptz default now()
);
create index idx_ventas_fecha on ventas(fecha);

create table venta_items (
  id uuid primary key default gen_random_uuid(),
  venta_id uuid references ventas(id) on delete cascade,
  ref text references productos(ref) on update cascade on delete set null,
  nombre text default '',
  cantidad integer not null check (cantidad > 0),
  precio numeric not null,
  subtotal numeric not null,
  costo_unitario numeric not null,
  costo_total numeric not null
);
create index idx_venta_items_ref on venta_items(ref);

create table entregas (
  id uuid primary key default gen_random_uuid(),
  venta_id uuid references ventas(id) on delete cascade unique not null,
  guia text default '',
  cliente_nombre text default 'Cliente',
  fecha date not null,
  monto numeric not null default 0,
  abono numeric not null default 0,
  saldo numeric not null default 0,
  empresa text default 'Por definir',
  created_at timestamptz default now()
);

create table pagos (
  id uuid primary key default gen_random_uuid(),
  entrega_id uuid references entregas(id) on delete cascade,
  fecha date not null,
  monto numeric not null,
  quien_paga text default 'Cliente',
  created_at timestamptz default now()
);

-- RLS: un solo usuario (la dueña) — basta con exigir sesión autenticada en cada tabla.
-- La seguridad real la da esto (RLS), no que la "anon key" del frontend sea secreta
-- (esa key es pública por diseño en cualquier app Supabase).
alter table productos enable row level security;
alter table clientes enable row level security;
alter table compras enable row level security;
alter table ventas enable row level security;
alter table venta_items enable row level security;
alter table entregas enable row level security;
alter table pagos enable row level security;

create policy "auth_full_access" on productos for all to authenticated using (true) with check (true);
create policy "auth_full_access" on clientes  for all to authenticated using (true) with check (true);
create policy "auth_full_access" on compras   for all to authenticated using (true) with check (true);
create policy "auth_full_access" on ventas    for all to authenticated using (true) with check (true);
create policy "auth_full_access" on venta_items for all to authenticated using (true) with check (true);
create policy "auth_full_access" on entregas  for all to authenticated using (true) with check (true);
create policy "auth_full_access" on pagos     for all to authenticated using (true) with check (true);
